### ISSUE TITLE
MNE-Qt-Browser always loading data into memory?

### ISSUE THREAD

**Issue by marsipu** [cbrnr/eeg-browsers#1]
Hi @cbrnr,

you write that MNE-Qt-Browser

> Requires all data to be available in memory

But with the `precompute`-parameter of [`mne.io.Raw.plot`](https://mne.tools/dev/generated/mne.io.Raw.html#mne.io.Raw.plot), one should also be able to deactivate loading all data into RAM.

**Comment by cbrnr** [comment]
Thanks @marsipu, I didn't know that! So this means that only the visible portion (plus minus some additional data around it maybe?) needs to be loaded into RAM? I will correct this ASAP!

**Comment by marsipu** [comment]
Yes, the code for this is in ll. 3905 of _pg_figure, where `_update_data` is overwritten for `MNEQtBrowser`.
To my knowledge when just indexing a Raw-object without preloading, the data gets loaded from the drive. I think `BaseRaw._read_segment` does that, using different methods depending on the file-format.

**Comment by cbrnr** [comment]
OK, so it doesn't work with all formats? I guess I will try some example files to see how this works.

**Comment by marsipu** [comment]
I don't see something that would indicate, that it shouldn't work for all formats

**Comment by cbrnr** [comment]
Fixed in latest `main`. Thanks @marsipu!
